### ISSUE TITLE
Images support

### ISSUE THREAD

**Issue by vala** [nickfrandsen/htmltoword#12]
Hi !

I'd like to know if images can be supported by your gem. I suppose not because it didn't worked for me and I can't see any reference to images or `<img>` tags in your source code (I only searched for it a bit).

If it is not supported yet, I'd be happy to try to implement it if you can guide me, since I don't know XSLT.

But I imagine some kind of HTML pre-processing to download images and reference them directly from inside the generated .docx "zip" file may do the trick - or maybe not ?

Thanks for your work though, it works nicely for the rest of the document, and a ruby solution is really appreciated here.

**Comment by swaminator** [comment]
Hi Nick,

I want to work on adding support for the <img> tag. Do let me know if you have any ideas (I have successfully added support to mathml)

**Comment by anitsirc** [comment]
Hi @swaminator maintenance of this repo has been moved to https://github.com/karnov/htmltoword

Please feel free to contribute there 

Cheers
