### ISSUE TITLE
Request: debug mode

### ISSUE THREAD

**Issue by archonic** [nickfrandsen/htmltoword#17]
I'm getting a lot of line breaks in my document. I'm not entirely sure what's being fed into the converter. WickedPDF can enable debug mode with a URL parameter. I'd like to do the same with htmltoword. Something like this:

http://domain.com/controller/export.docx?debug=true

If I have the time, I might be able to contribute this but time is short these days.

**Comment by anitsirc** [comment]
Hi @archonic, you can try the version of this gem https://github.com/karnov/htmltoword to see if you still get a lot of empty spaces. 

You can always unzip the docx file and check the contents of the `word/document.xml` file. If that doesn't help please create an issue on the new repo. 

Cheers
