### ISSUE TITLE
Setting fonts and sizes

### ISSUE THREAD

**Issue by jharbert** [nickfrandsen/htmltoword#19]
This is a feature request for the ability to set a font and font size for a document, paragraph, or both.

Looking into the WordprocessingML doc, it appears you can either explicitly list the font and size on a run every time, or create a document style and apply that style to the run.

Perhaps we could apply a font-size and font-family style to the body tag and have that body style propagate to all runs under it, or apply a style to a paragraph and have the run use that paragraphs style.

Something like this appears to work:

```
    <w:p>
      <w:r>
        <w:rPr>
          <w:sz w:val="50"/>
          <w:rFonts w:ascii="Times New Roman" />
        </w:rPr>
        <w:t xml:space="preserve">This paragraph is Times New Roman at 25pt</w:t>
      </w:r>
    </w:p>
```

**Comment by MadsBuus** [comment]
I think that setting up the proper  'styles' in the template document is a better way:
Copy the default.docx template, set up the default (normal) style, and perhaps headings with the styles and sizes you like, and just pass regular html using that.
Maintained version:
https://github.com/karnov/htmltoword
