### ISSUE TITLE
Support for Ruby 2.1.2

### ISSUE THREAD

**Issue by bonniecpk** [nickfrandsen/htmltoword#30]
After I bundle install the gem, when I load the library, this is what happened:

    [1] pry(main)> require 'htmltoword'
    NameError: constant Logger::Format not defined
    from /srv/scholar/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-1.4.0/lib/action_controller/support/clean_logger.rb:5:in `remove_const'

ruby version: 2.1.2

**Comment by chulkilee** [comment]
It is not the problem of Ruby 2.1.2. You're using pretty old version of actionpack.

**Comment by MadsBuus** [comment]
Close this please, development continued here: https://github.com/karnov/htmltoword
