### ISSUE TITLE
uninitialized constant ActionController::Responder

### ISSUE THREAD

**Issue by retorquere** [nickfrandsen/htmltoword#31]
It looks like the gem has a hard dependency on Rails

**Comment by chulkilee** [comment]
This can be fixed by using actionpack 4.1.x.

Rails 4.2 removes responder related code.

**Comment by AllThatIsTheCase** [comment]
If I install only actionpack 4.1.0, I get:

/home/emile/.rvm/gems/ruby-2.1.3@heroku/gems/htmltoword-0.2.0/lib/htmltoword/document.rb:74:in `read': No such file or directory @ rb_sysopen - /home/emile/.rvm/gems/ruby-2.1.3@heroku/gems/htmltoword-0.2.0/lib/htmltoword/xslt/html_to_wordml.xslt (Errno::ENOENT)
        from /home/emile/.rvm/gems/ruby-2.1.3@heroku/gems/htmltoword-0.2.0/lib/htmltoword/document.rb:74:in `replace_file'
        from /home/emile/.rvm/gems/ruby-2.1.3@heroku/gems/htmltoword-0.2.0/lib/htmltoword/document.rb:10:in `create'
        from ./test.rb:6:in `<main>'

**Comment by chulkilee** [comment]
That look strange - `/home/emile/.rvm/gems/ruby-2.1.3@heroku/gems/htmltoword-0.2.0/lib/htmltoword/xslt/html_to_wordml.xslt` should exist. gem uninstall and then gem install. Also you may need to use it with bundler to load specific version of actionpack

**Comment by AllThatIsTheCase** [comment]
Uninstall-reinstall yields the same error.
I do use bundler, but this Gemfile:

    #ruby=2.1.3
    #ruby-gemset=heroku

    ruby '2.1.3'

    source "https://rubygems.org"

    gem 'nokogiri'
    gem 'zip-zip'
    gem 'rubyzip'
    gem 'sinatra'
    gem 'thin'
    gem 'redcarpet'
    gem 'docx_generator'
    gem 'actionpack', '~> 4.1'
    gem 'htmltoword'

pulls in actionpack 4.2, even after I cleared the 'heroku' gemset before doing a `bundle install`:

    actionpack (4.2.0)
    actionview (4.2.0)
    activesupport (4.2.0)
    bigdecimal (1.2.4)
    builder (3.2.2)
    bundler (1.7.4)
    bundler-unload (1.0.2)
    daemons (1.1.9)
    docx_generator (0.1.1)
    erubis (2.7.0)
    eventmachine (1.0.4)
    executable-hooks (1.3.2)
    gem-wrappers (1.2.7)
    htmltoword (0.2.0)
    i18n (0.7.0)
    io-console (0.4.2)
    json (1.8.2, 1.8.1)
    loofah (2.0.1)
    mini_portile (0.6.2)
    minitest (5.5.1, 4.7.5)
    nokogiri (1.6.6.2)
    psych (2.0.5)
    rack (1.6.0)
    rack-protection (1.5.3)
    rack-test (0.6.3)
    rails-deprecated_sanitizer (1.0.3)
    rails-dom-testing (1.0.5)
    rails-html-sanitizer (1.0.1)
    rake (10.1.0)
    rdoc (4.1.0)
    redcarpet (3.2.2)
    rubygems-bundler (1.4.4)
    rubyzip (1.1.6)
    rvm (1.11.3.9)
    sinatra (1.4.5)
    test-unit (2.1.3.0)
    thin (1.6.3)
    thread_safe (0.3.4)
    tilt (1.4.1)
    tzinfo (1.2.2)
    zip-zip (0.3)

**Comment by chulkilee** [comment]
'~> 4.1' allows 4.2. You should use something like '< 4.2' so that Gemfile.lock does not include 4.2

If you're not using Rails, then check out #32 which removes hard dependency on ActionPack from htmltoword.

**Comment by AllThatIsTheCase** [comment]
If I do that, I get:

uninitialized constant ActionController::Renderers

**Comment by sriharshakappala** [comment]
Is there a way I can make this work on Rails 4.2? I am getting the below error

/home/harsha/.rvm/gems/ruby-2.2.0/gems/htmltoword-0.2.0/lib/htmltoword/action_controller.rb:41:in `<top (required)>': uninitialized constant ActionController::Responder (NameError)

**Comment by chulkilee** [comment]
@AllThatIsTheCase what is the output of bundle list?

@sriharshakappala try with `gem 'responders', '~> 2.0' `

**Comment by AllThatIsTheCase** [comment]
*** LOCAL GEMS ***

actionpack (2.3.2)
activesupport (4.2.0, 2.3.2)
bigdecimal (1.2.4)
builder (3.2.2)
bundler (1.7.4)
bundler-unload (1.0.2)
daemons (1.1.9)
docx_generator (0.1.1)
erubis (2.7.0)
eventmachine (1.0.4)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
htmltoword (0.2.0)
i18n (0.7.0)
io-console (0.4.2)
json (1.8.2, 1.8.1)
loofah (2.0.1)
mini_portile (0.6.2)
minitest (5.5.1, 4.7.5)
nokogiri (1.6.6.2)
psych (2.0.5)
rack (1.6.0)
rack-protection (1.5.3)
rack-test (0.6.3)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.5)
rails-html-sanitizer (1.0.1)
rake (10.1.0)
rdoc (4.1.0)
redcarpet (3.2.2)
rubygems-bundler (1.4.4)
rubyzip (1.1.6)
rvm (1.11.3.9)
sinatra (1.4.5)
test-unit (2.1.3.0)
thin (1.6.3)
thread_safe (0.3.4)
tilt (1.4.1)
tzinfo (1.2.2)
zip-zip (0.3)

**Comment by chulkilee** [comment]
@AllThatIsTheCase  no gem list but bundle list. That is the list of gem you actually use.

You can see there is two version of active support - 4.2.0 and 2.3.2. I tested it with 4.1.x.

**Comment by sriharshakappala** [comment]
@chulkilee Adding responders gem to my Gemfile fixed the issue. Thanks :+1:

**Comment by nickfrandsen** [comment]
@chulkilee thanks for the help with this gem. Would you like to become a maintainer of the library? Then you can help drive forward any enhancements that you might want. I am not using the library much so it has not seen as much development as it could.

**Comment by chulkilee** [comment]
I'm not using it right now neither, so I don't think I  Why don't you put some messages on README.md?

**Comment by anitsirc** [comment]
Hey guys,

Please check https://github.com/karnov/htmltoword. We have move maintenance over there and fix some of the things. 

Try it out and open a new issue there if this is still an issue
