### ISSUE TITLE
missing default template/xslt files in the gem install

### ISSUE THREAD

**Issue by jonknapp** [nickfrandsen/htmltoword#33]
I'm using RVM with Ruby 2.2.0 and when I try to use the gem I get path issues along the following lines:

```
Zip::Error (File /Users/jon/.rvm/gems/ruby-2.2.0@custom-gemset/gems/htmltoword-0.2.0/lib/htmltoword/templates/default.docx not found):
  app/controllers/welcome_controller.rb:6:in `block in index'
  app/controllers/welcome_controller.rb:5:in `index'
```

Looking in the gemset folder for the gem files shows they are not there either.

**Comment by jonknapp** [comment]
Looks like this got fixed in later commits.  I updated bundler to point to the `master` branch and it works without overriding the config.

Might be a good time to create a new version of the gem since anyone who installs `v0.2.0` is going to have a bad day.

**Comment by swaminator** [comment]
@jonknapp I'm having the same problem. After I do a gem install, the XSLT folder isn't copied over. Weirdly, the gem is still able to convert the basic HTML to a Word doc. Don't know how this is happening. How were you able to get the XSLT and template folder to get added to the gem?

**Comment by alepore** [comment]
:+1:

**Comment by anitsirc** [comment]
Hi, maintenance of this gem has been moved to https://github.com/karnov/htmltoword. Please try the newest version and report this issue if it still occurs
