### ISSUE TITLE
White space being added before and after element

### ISSUE THREAD

**Issue by prawdeeps** [nickfrandsen/htmltoword#37]
I created a word document using version 1.8 of htmltoword.  It was interpreted fine in Openoffice, but after trying to open with a copy of microsoft word, the software reported the file was corrupted.  I upgraded to version 2.0 and copied to the xslt to where I believe was the correct place, and regenerated the document.  This document could be opened in word, but alot of preserve whitespace xml nodes were added, creating undesirable formatting.  Is there something im missing here?  I removed everything complex in the end, and tried to just render a paragraph, but still excessive white space appeared above and below the paragraph in the produced word document.  I can attempt to write another xslt, but I'm wondering if there's anything obvious that ive missed....

**Comment by MadsBuus** [comment]
Could you try this fork?:

https://github.com/karnov/htmltoword
There has been a lot of cleanup in this gem. I think the version you are using are not 1.8?, but 0.1.8?
The maintained version above is a 0.4.0 now

**Comment by prawdeeps** [comment]
Hi mate, thanks for getting back to me :) i am indeed using 0.1.8, but I wrote another xslt to get the job done.  Thank you for your help though!
