### ISSUE TITLE
compilation error: element html xsltParseStylesheetProcess : document is not a stylesheet 

### ISSUE THREAD

**Issue by henrikj242** [nickfrandsen/htmltoword#38]
I am probably missing something obvious, but I have not yet succeeded in generating a docx file with this gem.
I'm running rails 4.2.0 with ruby 2.2.0
I've added the gem to my gemfile and bundle install
I noticed that the template and xslt files were not downloaded, so I downloaded them manually and saved them the lib directory.
 
I've tried messing around with the configuration i orderto point to the correct lib folder - both in the gem as well as in my rails project.

The mentioned error message appears here in my controller:
```
  def download
    respond_with(@case, content: '<html><body>some html</body></html>')
  end
```
Any help is greatly appreciated!

**Comment by anitsirc** [comment]
Hi @henrikj242 , could you try this one: https://github.com/karnov/htmltoword. 

We have fix some of the bugs and updated the gem version in rubygems as well, please open a new issue there if this still occurs. 

Cheers
