### ISSUE TITLE
Error while starting rails server after adding htmltoword gem

### ISSUE THREAD

**Issue by IgorOsa** [nickfrandsen/htmltoword#39]
I'm added to Gemfile <code>gem 'htmltoword', '0.2.0'</code> into a new rails 4.2.1 app. But than i starts a rails server an error appear.
<pre>/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/htmltoword-0.2.0/lib/htmltoword/action_controller.rb:41:in `<top (required)>': uninitialized constant ActionController::Responder (NameError)
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/htmltoword-0.2.0/lib/htmltoword.rb:26:in `require'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/htmltoword-0.2.0/lib/htmltoword.rb:26:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.5/lib/bundler/runtime.rb:76:in `require'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.5/lib/bundler/runtime.rb:72:in `each'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.5/lib/bundler/runtime.rb:72:in `block in require'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.5/lib/bundler/runtime.rb:61:in `each'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.5/lib/bundler/runtime.rb:61:in `require'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.5/lib/bundler.rb:134:in `require'
        from /vagrant/HtmlWordConverter/config/application.rb:7:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `require'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
</pre>
After removing gem rails server starts normally. What problem in? What versions of Ruby/Rails supported? I tried ruby versions 2.0, 2.1.5, 2.2.2 and Rails 4.2.1. Same problem persist.

**Comment by MadsBuus** [comment]
Hi Igor, could you try this one: 
https://github.com/karnov/htmltoword
We have cleaned it up quite a bit
